Rav 4558 Nulls First And Nulls Last Support In MSSql
datametica/calcite pull request #139
Opened 2021-01-07 07:33 UTC by roy-sounak

2021-01-07 14:59 UTC, soma-mondal approved these changes

2021-01-07 14:59 UTC, soma-mondal commented on core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
> +    String sqlLiteralForCaseCall = (!(nullsFirst && desc)) ? "1" : "0";
Please don't use negation here

2021-01-07 14:59 UTC, soma-mondal commented on core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
> +    String sqlLiteralForCaseCall = (!(nullsFirst && desc)) ? "1" : "0";
Please rename sqlLiteralForCaseCall and define else part here as well.

2021-01-13 07:22 UTC, soma-mondal requested changes
Please revert HiveSqlDialect changes

2021-01-13 07:30 UTC, soma-mondal commented
L1 Done

2021-01-13 07:30 UTC, soma-mondal approved these changes

2021-01-13 08:48 UTC, yogeshmuley approved these changes

2021-01-13 09:21 UTC, yogeshmuley approved these changes

2021-01-13 09:23 UTC, merged