Added INSTR Support for Synapse.
datametica/calcite pull request #156
Opened 2021-01-29 13:36 UTC by saranshmanglani

2021-01-29 14:13 UTC, roy-sounak requested changes

2021-01-29 14:13 UTC, roy-sounak commented on core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
> +        unparseTruncateAndRound(writer, call, leftPrec, rightPrec);
Revert this change into a seperate PR

2021-01-29 14:13 UTC, roy-sounak commented on core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
> +      unparseTruncateAndRound(writer, call, leftPrec, rightPrec);
Revert "truncate and Round" change into a seperate PR

2021-01-29 14:13 UTC, roy-sounak commented on core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
> +  private void unparseTruncateAndRound(
Revert "truncate and Round" change into a seperate PR

2021-02-01 13:16 UTC, roy-sounak approved these changes
LGTM!

2021-02-01 14:17 UTC, soma-mondal approved these changes

2021-02-01 14:55 UTC, merged