Concat and dayofmonth support for snowflake
datametica/calcite pull request #160
Opened 2021-02-01 09:53 UTC by rohitgaurDatametica

2021-02-01 11:09 UTC, roy-sounak requested changes

2021-02-01 11:09 UTC, roy-sounak commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final String synapse = "SELECT [employee_id]\n"
Please write a test in concatFunctionEmulationForHiveAndSparkAndBigQuery

2021-02-03 11:00 UTC, roy-sounak approved these changes
LGTM

2021-02-03 11:19 UTC, soma-mondal approved these changes

2021-02-03 11:19 UTC, merged