RAV-6169 big query comma join to cross join
datametica/calcite pull request #198
Opened 2021-06-16 11:49 UTC by ap-dm

2021-06-16 15:18 UTC, Technay approved these changes

2021-06-16 15:19 UTC, Technay commented
LGTM

2021-06-22 14:00 UTC, soma-mondal requested changes
Can we please add a test case ?

2021-06-22 14:03 UTC, yogeshmuley reviewed
Fix looks good.Please add test case in RelToSqlConverterTest.java file.

2021-06-22 14:28 UTC, yogeshmuley approved these changes

2021-06-22 14:56 UTC, yogeshmuley approved these changes

2021-06-23 06:45 UTC, soma-mondal approved these changes

2021-06-23 06:46 UTC, merged