Unparse truc function
datametica/calcite pull request #219
Opened 2021-10-07 07:38 UTC by ankit6130

2021-10-11 06:38 UTC, soma-mondal requested changes

2021-10-11 06:38 UTC, soma-mondal commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +        @Override public void unparse(SqlWriter writer, SqlCall call, int leftPrec, int rightPrec) {
We should not have unparse method in function defination

2021-10-18 12:35 UTC, praveendatametica commented
LGTM

2021-10-18 12:36 UTC, praveendatametica commented
LGTM

2021-10-18 17:06 UTC, merged