(RORAB-2948) Removing the optimization of ROW to RANGE
datametica/calcite pull request #360
Opened 2023-04-11 09:05 UTC by Kowsikraja

2023-04-24 12:41 UTC, dm-shantanuc requested changes

2023-04-24 12:41 UTC, dm-shantanuc commented on core/src/main/java/org/apache/calcite/rex/RexBuilder.java
> -    if (lowerBound.isUnbounded() && lowerBound.isPreceding()
Missing test cases on Calcite end.

2023-04-25 10:13 UTC, Kowsikraja commented on core/src/main/java/org/apache/calcite/rex/RexBuilder.java
> -    if (lowerBound.isUnbounded() && lowerBound.isPreceding()
Done

2023-04-26 12:00 UTC, dm-shantanuc requested changes

2023-04-26 12:41 UTC, Kowsikraja commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final String expectedOracleSql = "SELECT MAX() OVER (ORDER BY \"EMPNO\" ROWS BETWEEN "
Yeah ok , i will get back to you once done

2023-04-26 12:55 UTC, Kowsikraja commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final String expectedOracleSql = "SELECT MAX() OVER (ORDER BY \"EMPNO\" ROWS BETWEEN "
pushed the changes. please have a look

2023-04-26 13:16 UTC, dm-shantanuc approved these changes

2023-04-26 14:32 UTC, dm-shantanuc approved these changes
The changes look good.

2023-04-26 14:33 UTC, merged