After Split_part function fix
datametica/calcite pull request #438
Opened 2023-08-08 06:59 UTC by SaiTejaVenkatapuram

2023-08-25 04:41 UTC, Katakam-Phani-Mahidhar requested changes
Please make another operator in SqlLibraryOperators for safe array access in big query analogous to SqlStdOperatorTable.ITEM

2023-08-25 04:41 UTC, Katakam-Phani-Mahidhar commented on core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
> +    writer.print("[SAFE_OFFSET (");
refer SqlStdOperatorTable.ITEM for implementation of array access

2023-08-25 04:41 UTC, Katakam-Phani-Mahidhar commented on core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
> +        if (thirdOperand == 0) {
pls move this to BQConverterRexShuttle

2023-09-08 10:17 UTC, nosheenSheikh02 requested changes

2023-09-12 13:02 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +          OperandTypes.family(SqlTypeFamily.NULL, SqlTypeFamily.STRING, SqlTypeFamily.INTEGER)),
OperandTypes.family(SqlTypeFamily.NULL, SqlTypeFamily.STRING, SqlTypeFamily.INTEGER) changed to OperandTypes.NULL_STRING_INTEGER

2023-09-12 13:03 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
> +
Made changes as mentioned

2023-09-12 13:04 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/fun/SqlItemOperator.java
> +          .or(OperandTypes.family(SqlTypeFamily.CHARACTER));
Reverted back the changes

2023-09-12 13:05 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +import org.apache.calcite.sql.type.SqlTypeUtil;
Removed unused imports

2023-09-12 13:05 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +
Removed unused imports

2023-09-12 13:07 UTC, SaiTejaVenkatapuram commented on core/src/main/java/org/apache/calcite/sql/type/SqlSingleOperandTypeChecker.java
> +  }
Removed the changes.

2023-09-13 03:48 UTC, Katakam-Phani-Mahidhar commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +          .andThen(SqlTypeTransforms.TO_ARRAY),
The current return type derivation does not work when string type is added as an operand. So, this is added in order to get the current ReturnType.

2023-09-13 03:51 UTC, Katakam-Phani-Mahidhar commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +  }
As the SPLIT operator ReturnType is modified. this test case is added to test that change.

2023-09-15 06:44 UTC, nosheenSheikh02 approved these changes

2023-09-20 09:27 UTC, dm-shantanuc approved these changes
LGTM. Also reviewed by Anurag.

2023-09-20 09:54 UTC, dm-shantanuc approved these changes

2023-09-20 10:13 UTC, Katakam-Phani-Mahidhar approved these changes

2023-09-20 10:14 UTC, merged