Suuport for Convert_Timezone with two args for Snowflake
datametica/calcite pull request #444
Opened 2023-08-17 09:16 UTC by Rajeshwari4

2023-10-10 10:03 UTC, nosheenSheikh02 requested changes

2023-10-10 10:03 UTC, nosheenSheikh02 commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final String expectedBiqQuery =
make this expectedBigQuery

2023-10-10 10:03 UTC, nosheenSheikh02 commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final RexNode formatTimestampRexNode2 = builder.call(SqlLibraryOperators.FORMAT_TIMESTAMP,
make it `formatTimestampRexNode`

2023-10-10 10:03 UTC, nosheenSheikh02 commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +    final String expectedBiqQuery = "SELECT FORMAT_TIMESTAMP('%c%z', CURRENT_DATETIME()) AS FD2\n"
make this expectedBigQuery

2023-10-10 14:57 UTC, nosheenSheikh02 approved these changes

2023-10-11 11:58 UTC, dm-shantanuc approved these changes
LGTM

2023-10-11 12:10 UTC, merged