(RSFB-956) Added support for TRY_TO_TIME function
datametica/calcite pull request #474
Opened 2023-09-21 12:55 UTC by Kowsikraja

2023-11-08 06:38 UTC, nosheenSheikh02 commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +        builder.literal("01:02:03"), builder.literal("HH24:MI:SS"));
add one more node having invalid value

2023-11-08 06:40 UTC, nosheenSheikh02 requested changes

2023-11-08 06:40 UTC, nosheenSheikh02 commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
> +        builder.literal("01:02:03"), builder.literal("HH24:MI:SS"));
add one more node having invalid value

2023-11-29 11:46 UTC, dm-shantanuc approved these changes
LGTM

2023-11-29 11:51 UTC, nosheenSheikh02 approved these changes

2023-11-29 11:52 UTC, merged