RSFB:2082 - Adds one more oparand to SPLIT function
datametica/calcite pull request #516
Opened 2023-12-07 16:01 UTC by nirnaypatil11

2023-12-11 11:46 UTC, vinayujeedm requested changes

2023-12-11 11:46 UTC, vinayujeedm commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +      OperandTypes.or(OperandTypes.STRING_STRING_INTEGER,
Add test case.

2023-12-13 12:08 UTC, vinayujeedm approved these changes

2023-12-26 09:48 UTC, dm-shantanuc commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +  public static final SqlFunction SPLIT_WITH_INDEX = new SqlFunction(
Need to add test case for the same in Calcite code also.

2023-12-26 10:43 UTC, dm-shantanuc commented on core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
> +  public static final SqlFunction SPLIT_WITH_INDEX = new SqlFunction(
As discussed with Anurag, this is a temporary solution till GUDU issue is fixed. This code will be removed later. Hence allowing without test case.

2023-12-26 10:45 UTC, dm-shantanuc approved these changes

2023-12-26 10:45 UTC, merged