RSFB-2507 Regexp contains unparsing fixed
datametica/calcite pull request #584
Opened 2024-03-04 13:00 UTC by jitender-datametica

RSFB-2507

2024-03-08 12:56 UTC, nosheenSheikh02 requested changes

2024-03-08 13:24 UTC, jitender-datametica commented on core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java
> +        .project(builder.alias(regexpContainsRex, "regexpConatins"))
Done

2024-03-08 13:36 UTC, nosheenSheikh02 approved these changes

2024-03-11 08:55 UTC, deepakkadam-dm approved these changes
Already reviewed. Merging.

2024-03-11 08:56 UTC, merged